### ISSUE TITLE
REG_FULL_RESOURCE_DESCRIPTOR not supported

### ISSUE THREAD

**Issue by churstz** [gersonkurz/regdiff#4]
When exporting HKLM before making reg changes, the exception below was thrown.  Based on the error message and where the export stopped I suspect the issue is due to the unknown Key type of REG_FULL_RESOURCE_DESCRIPTOR which corresponds to the following regkey on a Win2K16 box

HKEY_LOCAL_MACHINE\\HARDWARE\DESCRIPTION\System\Configuration Data

Unhandled Exception: System.InvalidOperationException: ERROR, RegValueEntry <RegValueEntry: Configuration Data> has unsupported data type Unknown
   at com.tikumo.regis3.RegValueEntry.WriteRegFileFormat(TextWriter output)
   at com.tikumo.regis3.RegKeyEntry.WriteRegFileFormat(TextWriter output, RegFileExportOptions options)
   at com.tikumo.regis3.RegKeyEntry.WriteRegFileFormat(TextWriter output, RegFileExportOptions options)
   at com.tikumo.regis3.RegKeyEntry.WriteRegFileFormat(TextWriter output, RegFileExportOptions options)
   at com.tikumo.regis3.RegKeyEntry.WriteRegFileFormat(TextWriter output, RegFileExportOptions options)
   at com.tikumo.regis3.RegKeyEntry.WriteRegFileFormat(TextWriter output, RegFileExportOptions options)
   at com.tikumo.regis3.RegFileExporter.Export(RegKeyEntry key, TextWriter file, RegFileExportOptions options)
   at com.tikumo.regis3.RegFileExporter.Export(RegKeyEntry key, String filename, RegFileExportOptions options)
   at com.tikumo.regdiff.regdiff.HandleSingleFile()
   at com.tikumo.regdiff.regdiff.Run(String[] args)
   at com.tikumo.regdiff.regdiff.Main(String[] args)

**Comment by gersonkurz** [comment]
Sorry, I know: this is a bug in .NET actually. (Oh, and sorry for the long delay in answering ;))

If you look at https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.registryvaluekind?view=net-5.0, you'll see that the .NET registry API simply doesn't know about this type: it'll map it to "Unknown", and there is little I can do about it.

=> won't be fixed any time soon, I am afraid.

Note: regdiff still can read and compare  REG_FULL_RESOURCE_DESCRIPTOR; it just cannot handle it when dealing with the .NET registry API.
